name: Build and Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  vscode:
    uses: instruqt/lab-docker-images/.github/workflows/docker.yml@main
    with:
      context: vscode
    secrets: inherit